# Generated by Django 5.1.1 on 2024-09-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=121)),
                ('position', models.CharField(default='None', max_length=123)),
                ('number_of_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='check_12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_12', models.CharField(max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='create_election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('number_of_candidates', models.IntegerField(default=0)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_apis.users')),
            ],
        ),
    ]
