# Generated by Django 5.1.1 on 2024-09-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_election_creation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check_12',
        ),
    ]
