# Generated by Django 5.1.1 on 2024-09-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_election_creation', '0002_delete_check_12'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_election',
            name='unique_id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
